TAG_MAP = {
    # --- Major Genres ---
    "판타지": "Fantasy",
    "현대": "Modern",
    "현대판타지": "Modern Fantasy",
    "로맨스": "Romance",
    "로맨스판타지": "Romance Fantasy",
    "무협": "Martial Arts",
    "라이트노벨": "Light Novel",
    "일상": "Slice of Life",
    "코미디": "Comedy",
    "드라마": "Drama",
    "스릴러": "Thriller",
    "공포": "Horror",
    "SF": "Sci-Fi",
    "미스터리": "Mystery",
    "어반판타지": "Urban Fantasy",
    "대체역사": "Alternate History",
    "정통판타지": "High Fantasy",
    "퓨전무협": "Fusion Martial Arts",

    # --- Core Tropes ---
    "먼치킨": "Overpowered (OP)",
    "집착": "Obsession",
    "순애": "Pure Love",
    "하렘": "Harem",
    "착각": "Misunderstanding",
    "착각계": "Misunderstanding Style",
    "전생": "Reincarnation",
    "빙의": "Possession",
    "회귀": "Regression",
    "환생": "Rebirth",
    "피폐": "Angst/Depravity",
    "약피폐": "Light Angst",
    "성장": "Growth",
    "성장형": "Slow Growth",
    "후회": "Regret",
    "구원": "Salvation",
    "치유": "Healing",
    "복수": "Revenge",
    "아카데미": "Academy",
    "헌터": "Hunter",
    "게임": "Game",
    "게임빙의": "Game Possession",
    "시스템": "System",
    "상태창": "Status Window",
    "인외": "Non-Human",
    "아포칼립스": "Apocalypse",
    "TS": "Gender Bender",
    "TS히로인": "GB Heroine",
    "암타": "Female Depravity (TS)",
    "백합": "Yuri (GL)",
    "GL": "Girls Love",
    "노맨스": "No Romance",
    "남성향": "Male Oriented",
    "여주인공": "Female Protagonist",
    "얀데레": "Yandere",
    "나데나데": "Pampering",

    # --- Series & Fandoms ---
    "패러디": "Parody/Fanfic",
    "블루아카이브": "Blue Archive",
    "블루아카": "Blue Archive",
    "블아": "Blue Archive",
    "프문": "Project Moon",
    "프로젝트문": "Project Moon",
    "림버스": "Limbus Company",
    "림버스컴퍼니": "Limbus Company",
    "라오루": "Library of Ruina",
    "로보토미": "Lobotomy Corp",
    "포켓몬": "Pokemon",
    "포켓몬스터": "Pokemon",
    "주술회전": "Jujutsu Kaisen",
    "전독시": "ORV (Omniscient Reader)",
    "전지적독자시점": "Omniscient Reader",
    "원신": "Genshin Impact",
    "FATE": "Fate Series",
    "페이트": "Fate Series",
    "FGO": "Fate/Grand Order",
    "페그오": "Fate/Grand Order",
    "원피스": "One Piece",
    "나히아": "MHA (My Hero Academia)",
    "히로아카": "My Hero Academia",
    "니케": "NIKKE",
    "코노스바": "Konosuba",
    "해리포터": "Harry Potter",
    "워해머": "Warhammer",
    "데어라": "Date A Live",
    "블리치": "Bleach",
    "울트라킬": "ULTRAKILL",
    "유희왕": "Yu-Gi-Oh!",

    # --- NSFW & Niche Tags ---
    "19금": "R-18",
    "고수위": "High-Heat / Explicit",
    "성인": "Adult",
    "조교": "Training/Conditioning",
    "능욕": "Humiliation",
    "타락": "Corruption",
    "최면": "Hypnosis",
    "관음": "Voyeurism",
    "SM": "Sadism/Masochism",
    "BDSM": "BDSM",
    "역키잡": "Reverse Grooming",
    "쇼타": "Shota",
    "유부녀": "Married Woman / MILF",
    "MILF": "MILF",
    "절륜": "High Stamina/Vigor",
    "NTR": "NTR (Cuckoldry)",
    "NTL": "NTL (Stealing Heroine)",
    "역강간": "Reverse Rape",
    "남녀역전": "Gender Role Reversal",
    "소프트펨돔": "Soft Femdom",
    "펨돔": "Femdom",
    "후타나리": "Futanari",
    "촉수": "Tentacles",
    "근친": "Incest",
    "마사지": "Massage",
    "중세": "Medieval",
    "다중": "Multiple/Multi-POV",
    "유희생활": "Playful Life / Living for Fun",
    "사이다": "Refreshing (OP/Fast-paced)", # Literally 'Cider', refers to satisfying plot progression
    "다크판타지": "Dark Fantasy",
    "갤러리": "Gallery / Forum", # Usually refers to community-based tropes (like DCInside)
    "괴이": "Anomaly / Apparition",
    "가면라이더": "Kamen Rider",
    "괴담": "Ghost Story / Urban Legend",
    "액션": "Action",
    "2차창작": "Fanfiction / Secondary Creation",
    "이세계": "Isekai / Other World",
    "빌런": "Villain",
    "감금": "Confinement",
    "생존": "Survival",
    "재벌": "Chaebol / Tycoon",
    "던전": "Dungeon",
    "체인소맨": "Chainsaw Man",
    "힐링": "Healing",
    "히어로": "Hero"
}

def translate_tags(tag_string):
    """Translates a comma-separated string of Korean tags to English."""
    if not tag_string:
        return ""
    tags = tag_string.split(',')
    # Use the map, fallback to original tag if translation is missing
    translated = [TAG_MAP.get(t.strip(), t.strip()) for t in tags if t.strip()]
    return ", ".join(translated)
